---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - test/support/dummy.rb
    - vendor/**/*
    - bin/**/*
    - gemfiles/vendor/**/*

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
