---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - test/support/dummy.rb
    - vendor/**/*
    - bin/**/*
    - gemfiles/vendor/**/*

Metrics:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
